### ISSUE TITLE
Issue with onValid callback beeing executed multiple times

### ISSUE THREAD

**Issue by riftshadow** [Adyen/adyen-components-js-sample-code#5] opened 2019-10-15 12:56 UTC
Hey guys, 

we are implementing the new drop-in functionality for our website, I just updated the websdk from 3.0 to 3.2 and now either the onChange and also the onValid callbacks which you can pass to a CheckoutConfiguration objects gets called multiple times. 

For example, i have a CC form which is beeing shown up for our customers, we are using the onValid callback to send a XHR to our backend with the information from the SecureFields.

It works great but for some reasons it always gets called twice after entering on the of the Test Numbers.

Greetings from Munich,

**Comment by marcperez** [comment] 2019-10-25 13:05
Hey Karl,

Thanks for letting us know. We've found the root cause of this issue and it will be fixed on the next version. 

If you have any other question about our integrations, please contact our [support team](https://support.adyen.com/hc/en-us).

**Closed as completed by marcperez** 2019-10-25 13:05 UTC
